### ISSUE TITLE
 dnf module install X11-base fails

### ISSUE THREAD

**Issue by whitel** [modularity-modules/X11-base#1]
-------------------------------` DNF ----------------------------------
    Installed Packages
    dnf.noarch                             2.7.3-1.module_e1d44a88.modularity.1.3fb9e5c                          @anaconda
    libdnf.x86_64                          0.10.1-2.module_e1d44a88.modularity.1                                 @anaconda
    ----------------------------------------------------------------------
    Image built with (KOJI composes):
                    GIT:            https://github.com/container-images/boltron-27
                    Base:           Fedora-Modular-Bikeshed-20171011.n.0
    Image running aginst (KOJI Composes):
                    Bike:   Fedora-Modular-Bikeshed-20171012.n.0

    $ dnf module install X11-base
    Fedora - Bikeshed - Developmental packages for the next Fedora release
    Last metadata expiration check: 0:00:00 ago on Fri 13 Oct 2017 02:34:41 PM UTC.
    Error: 
     Problem 1: conflicting requests
      - nothing provides libfontconfig.so.1()(64bit) needed by libXft-2.3.2-7.module_1498444e.x86_64
     Problem 2: conflicting requests
      - nothing provides autoconf needed by xorg-x11-util-macros-1.19.0-7.module_1498444e.noarch
    Boltron-27-7a9bbf282663-1#

**Comment by alexxa** [comment]
@KarstenHopp

**Comment by nphilipp** [comment]
Just to sum up what we talked about before, the `fontconfig` and `autoconf` packages which satisfy these deps are in the `fonts` and `autotools` modules, respectively. Both modules are a runtime dependency of `X11-base`, so the issue would be solved by DNF enabling both modules together with `X11-base`. If I manually enable them, installing `X11-base` works for me:

```
Boltron-27-6d111890edc5-1# dnf module install X11-base
Last metadata expiration check: 3:55:02 ago on Fri 13 Oct 2017 12:11:12 PM UTC.
Error: 
 Problem 1: conflicting requests
  - nothing provides libfontconfig.so.1()(64bit) needed by libXft-2.3.2-7.module_1498444e.x86_64
 Problem 2: conflicting requests
  - nothing provides autoconf needed by xorg-x11-util-macros-1.19.0-7.module_1498444e.noarch
Boltron-27-6d111890edc5-1# dnf module enable autotools fonts
Last metadata expiration check: 3:55:16 ago on Fri 13 Oct 2017 12:11:12 PM UTC.
'autotools' is enabled
'fonts' is enabled
Boltron-27-6d111890edc5-0# dnf module install X11-base
Last metadata expiration check: 3:55:29 ago on Fri 13 Oct 2017 12:11:12 PM UTC.
Dependencies resolved.
==============================================================================================================================================================================================
 Package                                     Arch                       Version                                                             Repository                                   Size
==============================================================================================================================================================================================
Installing module packages:
 libICE                                      x86_64                     1.0.9-11.module_1498444e                                            modular-bikeshed-server                      71 k
 libSM                                       x86_64                     1.2.2-7.module_1498444e                                             modular-bikeshed-server                      44 k
 libX11                                      x86_64                     1.6.5-4.module_1498444e                                             modular-bikeshed-server                     616 k
 libX11-common                               noarch                     1.6.5-4.module_1498444e                                             modular-bikeshed-server                     166 k
 libXau                                      x86_64                     1.0.8-9.module_1498444e                                             modular-bikeshed-server                      34 k
 libXcomposite                               x86_64                     0.4.4-11.module_1498444e                                            modular-bikeshed-server                      27 k
...
```

Here are the relevant Bugzilla tickets for enabling dependency modules when installing and upgrading modules:

https://bugzilla.redhat.com/show_bug.cgi?id=1484014  
https://bugzilla.redhat.com/show_bug.cgi?id=1484017

And here's the pull request which may implement at least the installation side (still waiting on feedback from mhatina to confirm):

https://github.com/rpm-software-management/dnf/pull/951

**Comment by KarstenHopp** [comment]
latest reports found no issues anymore. closing
